### ISSUE TITLE
Unable to execute nomad command from inside client node

### ISSUE THREAD

**Issue by BenStuart** [greenthegarden/home-cloud-native-platform#13]
Host OS:
Windwos 10 Business
Version 1903
OS Build 18362.295

```
PS C:\Users\BenStuart\_ROOT\home\home-cloud-native-platform-master> vagrant status
{"ip_range"=>"172.16.1", "ip_netmask"=>"255.255.255.0", "hcnp_node_count"=>3}
Node name set to compute-node-1
Node IP address set to 172.16.1.10
Node name set to compute-node-2
Node IP address set to 172.16.1.11
Node name set to compute-node-3
Node IP address set to 172.16.1.12
Current machine states:

compute-node-1            running (virtualbox)
compute-node-2            running (virtualbox)
compute-node-3            running (virtualbox)
dns-node                  running (virtualbox)
gateway-node              running (virtualbox)
ansible-node              running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
PS C:\Users\BenStuart\_ROOT\home\home-cloud-native-platform-master> vagrant ssh compute-node-1
{"ip_range"=>"172.16.1", "ip_netmask"=>"255.255.255.0", "hcnp_node_count"=>3}
Node name set to compute-node-1
Node IP address set to 172.16.1.10
Node name set to compute-node-2
Node IP address set to 172.16.1.11
Node name set to compute-node-3
Node IP address set to 172.16.1.12
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-159-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

1 package can be updated.
0 updates are security updates.

New release '18.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Tue Aug 27 05:54:03 2019 from 172.16.1.3
vagrant@compute-node-1:~$ nomad
No command 'nomad' found, did you mean:
 Command 'numad' from package 'numad' (universe)
nomad: command not found
vagrant@compute-node-1:~$
```

**Comment by BenStuart** [comment]
Install log
[https://filebin.net/2vgmcmottr02u46k/install-log.txt?t=sujusj2b](url)

**Comment by brooms** [comment]
Looks like in the log the provisioning process failed prior to installing nomad.

`TASK [brianshumate.consul : Create configuration] ******************************
fatal: [compute-node-2.testdomain]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: The ipwrap filter requires python's netaddr be installed on the ansible controller"}
fatal: [compute-node-1.testdomain]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: The ipwrap filter requires python's netaddr be installed on the ansible controller"}
fatal: [compute-node-3.testdomain]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: The ipwrap filter requires python's netaddr be installed on the ansible controller"}`

This is related to issue #5.

Suggest running `vagrant provision` again to complete the process.

**Comment by BenStuart** [comment]
running vagrant provision, seems to have completed the process and nomad is now available.

**Comment by brooms** [comment]
Resolved, closing issue.
